apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - path: patches/patch-cm-cdk.yaml
    target:
      kind: ConfigMap
      name: file-service-config
      namespace: file-service
  - path: patches/patch-deployment-cdk.yaml
    target:
      kind: Deployment
      name: file-service-app
      namespace: file-service