apiVersion: v1
data:
  mapRoles: "- rolearn: arn:aws:iam::532673134317:role/piercuta-dev-karpenter-node-role\n\
    \  username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n\
    \    - system:nodes\n- rolearn: arn:aws:iam::532673134317:role/piercuta-dev-eks-node-role\n\
    \  username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n\
    \    - system:nodes\n"
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
