apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - patches/external-secret-sg.yaml  # Ajouter l'ExternalSecret


patches:
  - path: patches/patch-hpa-cdk.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: fastapi-hpa
      namespace: fastapi
  - path: patches/patch-hpa.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: fastapi-hpa
      namespace: fastapi
  - path: patches/patch-cm-cdk.yaml
    target:
      kind: ConfigMap
      name: fastapi-config
      namespace: fastapi
  - path: patches/patch-deployment-cdk.yaml
    target:
      kind: Deployment
      name: fastapi-app
      namespace: fastapi
  - path: patches/patch-sg-cdk.yaml
    target:
      kind: SecurityGroupPolicy
      name: fastapi-sg
      namespace: fastapi

vars:
  - name: SG_ID
    objref:
      kind: Secret
      name: fastapi-sg-secret
      apiVersion: v1
    fieldref:
      fieldpath: data.SG_ID
# # ExternalSecret pour la SG_ID qui va créé un secret que lon pourra récupérer à tester...
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: fastapi-sg












#   namespace: fastapi
# spec:
#   secretStoreRef:
#     name: aws-parameter-store
#     kind: ClusterSecretStore
#   target:
#     name: fastapi-sg
#   data:
#     - secretKey: SG_ID
#       remoteRef:
#         key: /network/fastapi/sg_id
