apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.name }}
  name: {{ .Values.service.name }}
  {{- else }}
  name: {{ include "fastapi.fullname" . }}-service
  {{- end }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "fastapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "fastapi.selectorLabels" . | nindent 4 }}
