apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-ingress.yaml

# patches:
#   - path: patch-aws-lb-syncwave.yaml
#     target:
#       kind: Deployment
#       name: aws-load-balancer-controller
#       namespace: kube-system