apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: aws-load-balancer-controller
    repo: https://aws.github.io/eks-charts
    version: 1.8.2
    releaseName: aws-load-balancer-controller
    includeCRDs: true
    namespace: kube-system
    valuesFile: alb-controller-values-cdk.yaml

# resources:
#   - ../base

patches:
  # - path: patches/patch-argocd-ingress.yaml
  #   target:
  #     kind: Ingress
  #     name: argocd-ingress
  #     namespace: argocd
  - path: patches/patch-aws-lb-syncwave.yaml
    target:
      kind: Deployment
      name: aws-load-balancer-controller
      namespace: kube-system