apiVersion: karpenter.k8s.aws/v1
kind: NodePool
metadata:
  name: karpenter-node-pool
  namespace: kube-system
spec:
  template:
    spec:
      # terminationGracePeriod: 1m
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]  # 💸 Spot = cheaper for dev purposes
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: [
            "t", 
            "c", 
            "m", 
            "r"
          ]  # 👈 Ajoute "t" pour les petits workloads (ex: t3, t4g)
        - key: "karpenter.k8s.aws/instance-family" # 👈 Exclude t3, t3a, t4g for security group for pods
          operator: NotIn
          values: ["t3", "t3a", "t4g"]
        - key: "karpenter.k8s.aws/instance-hypervisor" # 👈 Selector for security group for pods
          operator: In
          values: ["nitro"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
        - key: karpenter.k8s.aws/instance-cpu
          operator: Gt
          values: ["1"]  # ✅ Minimum 2 vCPU pour éviter les trop petites instances
  disruption:
    budgets:
    - nodes: 100% # ✅ 100% to avoid keeping few nodes on big instance type...
      reasons:
      - "Underutilized"
      - "Empty"
      - "Drifted"
