apiVersion: v1
kind: Service
metadata:
  name: file-service-svc
  namespace: file-service
  labels:
    app: file-service
spec:
  type: ClusterIP
  selector:
    app: file-service
  ports:
  - port: 80
    targetPort: 8000