apiVersion: v1
kind: ServiceAccount
metadata:
  name: file-service-sa
  namespace: file-service
  labels:
    app: file-service
  # annotations:
  #   eks.amazonaws.com/role-arn: ${SERVICE_ACCOUNT_ROLE_ARN} # <-- ARN du rôle IAM lié (facultatif si tu fais de l'IRSA)