apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
stringData:
  admin.password: $2a$10$7iiApYJIG.RQf4PuwOaaQOqsvlAx/vIYxV.5iJJxjQk6sQb69nbu.
  admin.passwordMtime: "2025-09-10T12:00:00Z"