env:
  CLOUDFRONT_DOMAIN: media-api-dev.piercuta.com
  S3_BUCKET_NAME: piercuta-dev-media-bucket
image:
  repository: 532673134317.dkr.ecr.eu-west-1.amazonaws.com/services/eks/file-service
  tag: dev
replicaCount: 1
resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 1000m
    memory: 512Mi
