prometheus:
  prometheusSpec:
    # Resource limits
    resources:
      requests:
        memory: 2Gi
        cpu: 1000m
      limits:
        memory: 4Gi
        cpu: 2000m
alertmanager:
  enabled: false
grafana:
  enabled: true
  adminUser: admin
  adminPassword: prom-operator