apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fastapi-hpa
  namespace: fastapi
  labels:
    app: fastapi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastapi-app
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  #   resource:
  #     name: memory
  #     target:
  #       type: AverageValue
  #       averageValue: 500Mi
  behavior:
    scaleDown:
      policies:
        - periodSeconds: 30
          type: Percent
          value: 75
      selectPolicy: Max
    scaleUp:
      policies:
        - periodSeconds: 15
          type: Percent
          value: 100
        - periodSeconds: 15
          type: Pods
          value: 5
      selectPolicy: Max
      stabilizationWindowSeconds: 0