apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - path: patches/patch-argocd-ingress-cdk.yaml
    target:
      kind: Ingress
      name: argocd-ingress
      namespace: argocd
  - path: patches/patch-fastapi-ingress-cdk.yaml
    target:
      kind: Ingress
      name: fastapi-ingress
      namespace: fastapi